python3 test.py input1.txt output1.txt
python3 test.py input2.txt output2.txt
python3 test.py input3.txt output3.txt
python3 test.py input4.txt output4.txt
python3 test.py input5.txt output5.txt
python3 test.py input6.txt output6.txt
python3 test.py input7.txt output7.txt
python3 test.py input8.txt output8.txt
python3 test.py input9.txt output9.txt
python3 test.py input10.txt output10.txt
